from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable
from os import PathLike
from types import TracebackType
from typing import Literal, final

__all__ = [
    "Ack",
    "AdvertPath",
    "AmbiguousContactError",
    "AuthenticationError",
    "AutoAddConfig",
    "BackpressureError",
    "Client",
    "ClientClosedError",
    "ConfigurationError",
    "Contact",
    "ContactUri",
    "CustomVariable",
    "CustomVariables",
    "DefaultFloodScope",
    "DeviceInfo",
    "DeviceRejectedError",
    "DeviceStats",
    "DisconnectedError",
    "DiscoveredDevice",
    "DiscoveryError",
    "Event",
    "EventStream",
    "FrequencyRange",
    "InvalidArgumentError",
    "MeshcoreError",
    "Message",
    "MessageStream",
    "ProtocolError",
    "SelfInfo",
    "SendReceipt",
    "StreamLaggedError",
    "TelemetryResponse",
    "TimeoutError",
    "TransportError",
    "TuningParams",
    "UnsupportedFeatureError",
    "__version__",
    "discover_ble",
    "discover_serial",
]

__version__: str

class MeshcoreError(Exception): ...
class ConfigurationError(MeshcoreError): ...
class DiscoveryError(MeshcoreError): ...
class TransportError(MeshcoreError): ...
class ProtocolError(MeshcoreError): ...
class DeviceRejectedError(ProtocolError): ...
class TimeoutError(MeshcoreError): ...
class DisconnectedError(TransportError): ...
class InvalidArgumentError(MeshcoreError): ...
class AmbiguousContactError(InvalidArgumentError): ...
class BackpressureError(TransportError): ...
class StreamLaggedError(MeshcoreError): ...
class UnsupportedFeatureError(MeshcoreError): ...
class AuthenticationError(MeshcoreError): ...
class ClientClosedError(MeshcoreError): ...

@final
class Contact:
    @property
    def public_key(self) -> str: ...
    @property
    def contact_type(self) -> str: ...
    @property
    def flags(self) -> int: ...
    @property
    def route(self) -> Literal["flood", "path"]: ...
    @property
    def route_hash_mode(self) -> int | None: ...
    @property
    def route_hop_count(self) -> int | None: ...
    @property
    def path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def last_advert(self) -> int: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def last_modified(self) -> int: ...

@final
class Message:
    @property
    def source(self) -> Literal["direct", "channel"]: ...
    @property
    def sender(self) -> str:
        """Direct key prefix, or ``channel:<decimal index>`` for a channel message."""
    @property
    def source_key_prefix(self) -> str | None: ...
    @property
    def channel(self) -> int | None: ...
    @property
    def route(self) -> Literal["direct", "path"]: ...
    @property
    def route_hash_mode(self) -> int | None: ...
    @property
    def route_hop_count(self) -> int | None: ...
    @property
    def text_type(self) -> int: ...
    @property
    def sender_timestamp(self) -> int: ...
    @property
    def signature(self) -> bytes | None: ...
    @property
    def text(self) -> str: ...
    @property
    def snr(self) -> float | None: ...
    @property
    def status(self) -> Literal["received", "queued", "sent", "acked", "failed"]: ...
    @property
    def failure_reason(self) -> str | None: ...
    @property
    def suggested_timeout_ms(self) -> int | None: ...

@final
class Ack:
    @property
    def code(self) -> bytes: ...
    @property
    def code_hex(self) -> str: ...
    @property
    def trip_time_ms(self) -> int | None: ...

@final
class SendReceipt:
    @property
    def ack_code(self) -> bytes: ...
    @property
    def code_hex(self) -> str: ...
    @property
    def suggested_timeout_ms(self) -> int: ...
    @property
    def suggested_timeout(self) -> float: ...

@final
class SelfInfo:
    @property
    def advertising_type(self) -> int: ...
    @property
    def tx_power(self) -> int: ...
    @property
    def max_tx_power(self) -> int: ...
    @property
    def public_key(self) -> str: ...
    @property
    def latitude(self) -> float: ...
    @property
    def longitude(self) -> float: ...
    @property
    def multi_acks(self) -> int: ...
    @property
    def advert_location_policy(self) -> int: ...
    @property
    def telemetry_mode_environment(self) -> int: ...
    @property
    def telemetry_mode_location(self) -> int: ...
    @property
    def telemetry_mode_base(self) -> int: ...
    @property
    def manual_add_contacts(self) -> bool: ...
    @property
    def radio_frequency_mhz(self) -> float: ...
    @property
    def radio_bandwidth_khz(self) -> float: ...
    @property
    def radio_spreading_factor(self) -> int: ...
    @property
    def radio_coding_rate(self) -> int: ...
    @property
    def name(self) -> str: ...

@final
class DeviceInfo:
    @property
    def protocol_version(self) -> int: ...
    @property
    def max_contacts(self) -> int | None: ...
    @property
    def max_channels(self) -> int | None: ...
    @property
    def firmware_build(self) -> str | None: ...
    @property
    def model(self) -> str | None: ...
    @property
    def firmware_version(self) -> str | None: ...
    @property
    def repeat_enabled(self) -> bool | None: ...
    @property
    def path_hash_mode(self) -> int | None: ...

@final
class ContactUri:
    @property
    def uri(self) -> str: ...
    @property
    def card(self) -> bytes: ...

@final
class TuningParams:
    @property
    def rx_delay(self) -> int: ...
    @property
    def airtime_factor(self) -> int: ...

@final
class CustomVariable:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...

@final
class CustomVariables:
    @property
    def raw(self) -> bytes: ...
    @property
    def entries(self) -> list[CustomVariable]: ...

@final
class AdvertPath:
    @property
    def received_at(self) -> int: ...
    @property
    def route(self) -> Literal["flood", "path"]: ...
    @property
    def route_hash_mode(self) -> int | None: ...
    @property
    def route_hop_count(self) -> int | None: ...
    @property
    def path(self) -> str: ...

@final
class DeviceStats:
    @property
    def kind(self) -> Literal["core", "radio", "packets"]: ...
    @property
    def battery_mv(self) -> int | None: ...
    @property
    def uptime_seconds(self) -> int | None: ...
    @property
    def errors(self) -> int | None: ...
    @property
    def queue_length(self) -> int | None: ...
    @property
    def noise_floor(self) -> int | None: ...
    @property
    def last_rssi(self) -> int | None: ...
    @property
    def last_snr(self) -> float | None: ...
    @property
    def tx_airtime_seconds(self) -> int | None: ...
    @property
    def rx_airtime_seconds(self) -> int | None: ...
    @property
    def received(self) -> int | None: ...
    @property
    def sent(self) -> int | None: ...
    @property
    def flood_received(self) -> int | None: ...
    @property
    def flood_sent(self) -> int | None: ...
    @property
    def direct_received(self) -> int | None: ...
    @property
    def direct_sent(self) -> int | None: ...
    @property
    def receive_errors(self) -> int | None: ...

@final
class TelemetryResponse:
    @property
    def source_key_prefix(self) -> str: ...
    @property
    def payload(self) -> bytes: ...

@final
class AutoAddConfig:
    @property
    def config(self) -> int: ...
    @property
    def max_hops(self) -> int | None: ...

@final
class FrequencyRange:
    @property
    def lower_khz(self) -> int: ...
    @property
    def upper_khz(self) -> int: ...

@final
class DefaultFloodScope:
    @property
    def state(self) -> Literal["unconfigured", "configured"]: ...
    @property
    def name(self) -> str | None: ...

_EventKind = Literal[
    "connected",
    "disconnected",
    "contacts",
    "self_info",
    "device_info",
    "message",
    "channel_info",
    "ack",
    "message_sent",
    "current_time",
    "battery",
    "contact_uri",
    "tuning_params",
    "custom_variables",
    "advert_path",
    "device_stats",
    "telemetry",
    "auto_add_config",
    "allowed_repeat_frequencies",
    "default_flood_scope",
    "control_data",
    "unsupported",
    "inbox_empty",
    "messages_waiting",
    "protocol_error",
    "unknown_packet",
]

@final
class Event:
    @property
    def kind(self) -> _EventKind: ...
    @property
    def message(self) -> Message | None: ...
    @property
    def ack(self) -> Ack | None: ...
    @property
    def self_info(self) -> SelfInfo | None: ...
    @property
    def device_info(self) -> DeviceInfo | None: ...
    @property
    def contacts(self) -> list[Contact] | None: ...
    @property
    def last_modified(self) -> int | None: ...
    @property
    def channel(self) -> int | None: ...
    @property
    def channel_name(self) -> str | None: ...
    @property
    def channel_secret_hash(self) -> int | None: ...
    @property
    def destination_type(self) -> int | None: ...
    @property
    def ack_code(self) -> bytes | None: ...
    @property
    def suggested_timeout_ms(self) -> int | None: ...
    @property
    def timestamp(self) -> int | None: ...
    @property
    def battery_level(self) -> int | None: ...
    @property
    def storage_used_kb(self) -> int | None: ...
    @property
    def storage_total_kb(self) -> int | None: ...
    @property
    def error(self) -> str | None: ...
    @property
    def unknown_code(self) -> int | None: ...
    @property
    def unknown_payload(self) -> bytes | None: ...
    @property
    def control_snr_qdb(self) -> int | None: ...
    @property
    def control_rssi_dbm(self) -> int | None: ...
    @property
    def control_path_len(self) -> int | None: ...
    @property
    def control_payload(self) -> bytes | None: ...
    @property
    def contact_uri(self) -> ContactUri | None: ...
    @property
    def tuning_params(self) -> TuningParams | None: ...
    @property
    def custom_variables(self) -> CustomVariables | None: ...
    @property
    def advert_path(self) -> AdvertPath | None: ...
    @property
    def device_stats(self) -> DeviceStats | None: ...
    @property
    def telemetry(self) -> TelemetryResponse | None: ...
    @property
    def auto_add_config(self) -> AutoAddConfig | None: ...
    @property
    def allowed_repeat_frequencies(self) -> list[FrequencyRange] | None: ...
    @property
    def default_flood_scope(self) -> DefaultFloodScope | None: ...

@final
class DiscoveredDevice:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def transport(self) -> Literal["ble", "serial", "tcp", "scripted", "unknown"]: ...
    @property
    def address(self) -> str | None: ...
    @property
    def port(self) -> int | None: ...
    @property
    def baud(self) -> int | None: ...
    @property
    def selector(self) -> str | None: ...
    @property
    def rssi(self) -> int | None: ...
    @property
    def notes(self) -> list[str]: ...

@final
class EventStream(AsyncIterator[Event]):
    def __aiter__(self) -> EventStream: ...
    def __anext__(self) -> Awaitable[Event]: ...

@final
class MessageStream(AsyncIterator[Message]):
    def __aiter__(self) -> MessageStream: ...
    def __anext__(self) -> Awaitable[Message]: ...

@final
class Client:
    @classmethod
    def auto(
        cls,
        *,
        profile: str | None = ...,
        config_path: str | PathLike[str] | None = ...,
    ) -> Awaitable[Client]: ...
    @classmethod
    def tcp(
        cls,
        host: str,
        port: int = ...,
        *,
        connect_timeout: float = ...,
        request_timeout: float = ...,
    ) -> Awaitable[Client]: ...
    @classmethod
    def serial(
        cls,
        port: str,
        *,
        baud: int = ...,
        connect_timeout: float = ...,
        request_timeout: float = ...,
    ) -> Awaitable[Client]: ...
    @classmethod
    def ble(
        cls,
        selector: str,
        *,
        connect_timeout: float = ...,
        request_timeout: float = ...,
    ) -> Awaitable[Client]: ...
    @classmethod
    def demo(cls, *, request_timeout: float = ...) -> Awaitable[Client]: ...
    @property
    def transport(self) -> Literal["ble", "serial", "tcp", "demo"]: ...
    @property
    def profile_name(self) -> str | None: ...
    @property
    def request_timeout(self) -> float: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def self_info(self) -> SelfInfo: ...
    def events(self) -> EventStream: ...
    def messages(self) -> MessageStream: ...
    def list_contacts(self, last_modified: int | None = ...) -> Awaitable[list[Contact]]: ...
    def send(self, contact: str, text: str, *, attempt: int = ...) -> Awaitable[SendReceipt]: ...
    def send_direct(
        self, destination: str | bytes, text: str, *, attempt: int = ...
    ) -> Awaitable[SendReceipt]: ...
    def send_command(
        self, destination: str | bytes, command: str, *, attempt: int = ...
    ) -> Awaitable[SendReceipt]: ...
    def send_channel(self, channel: int, text: str, *, text_type: int = ...) -> Awaitable[None]: ...
    def fetch_queued_message(self) -> Awaitable[Message | None]: ...
    def wait_for_ack(
        self,
        receipt_or_code: SendReceipt | str | bytes,
        *,
        timeout: float | None = ...,
    ) -> Awaitable[Ack]: ...
    def device_info(self) -> Awaitable[DeviceInfo]: ...
    def disconnect(self) -> Awaitable[None]: ...
    def reconnect(self) -> Awaitable[SelfInfo]: ...
    def shutdown(self) -> Awaitable[None]: ...
    def telemetry(
        self, kind: Literal["core", "radio", "packets"] = ...
    ) -> Awaitable[DeviceStats]: ...
    def self_telemetry(self) -> Awaitable[TelemetryResponse]: ...
    def __aenter__(self) -> Awaitable[Client]: ...
    def __aexit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> Awaitable[None]: ...

def discover_ble(*, timeout: float = ...) -> Awaitable[list[DiscoveredDevice]]: ...
def discover_serial() -> Awaitable[list[DiscoveredDevice]]: ...
