#!/usr/bin/env python3
"""Render the public Python typing stub as a deterministic Markdown API reference."""

from __future__ import annotations

import argparse
import ast
import difflib
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / "crates/meshquill-python/python/meshcore_sdk/_native.pyi"
OUTPUT = ROOT / "docs/reference/python-api.md"


def public_exports(tree: ast.Module) -> list[str]:
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if isinstance(value, list) and all(isinstance(item, str) for item in value):
                return value
    raise ValueError(f"{STUB} has no literal __all__ list")


def named_nodes(tree: ast.Module) -> dict[str, ast.AST]:
    nodes: dict[str, ast.AST] = {}
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            nodes[node.name] = node
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            nodes[node.target.id] = node
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    nodes[target.id] = node
    return nodes


def declaration(source_lines: list[str], node: ast.AST) -> str:
    start = node.lineno
    decorators = getattr(node, "decorator_list", [])
    if decorators:
        start = min(start, *(decorator.lineno for decorator in decorators))
    end = node.end_lineno
    if end is None:
        raise ValueError(f"AST node on line {start} has no end line")
    return "\n".join(source_lines[start - 1 : end]).rstrip()


def kind(node: ast.AST) -> str:
    if isinstance(node, ast.ClassDef):
        return "class"
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return "function"
    return "value"


def sections(
    names: Iterable[str], nodes: dict[str, ast.AST], source_lines: list[str]
) -> list[str]:
    rendered: list[str] = []
    for name in names:
        node = nodes.get(name)
        if node is None:
            raise ValueError(f"public export {name!r} has no declaration in {STUB}")
        rendered.extend(
            [
                f"## `{name}`",
                "",
                f"Public {kind(node)}.",
                "",
                "```python",
                declaration(source_lines, node),
                "```",
                "",
            ]
        )
    return rendered


def render() -> str:
    source = STUB.read_text(encoding="utf-8")
    source_lines = source.splitlines()
    tree = ast.parse(source, filename=str(STUB), type_comments=True)
    exports = public_exports(tree)
    nodes = named_nodes(tree)

    lines = [
        "# Python SDK API reference",
        "",
        "<!-- Generated by scripts/generate-python-api.py; do not edit by hand. -->",
        "",
        "This reference is generated from the installed package's authoritative typing stub. See",
        "[the Python SDK guide](../python-sdk.md) for lifecycle, cancellation and task-oriented",
        "examples.",
        "",
        "All async operations return `Awaitable[...]`; await them from an active `asyncio` event",
        "loop. Public classes are immutable unless their declaration says otherwise.",
        "",
        "## Supporting type aliases",
        "",
        "The following private alias defines the closed set returned by the public `Event.kind`",
        "property.",
        "",
        "```python",
        declaration(source_lines, nodes["_EventKind"]),
        "```",
        "",
    ]
    lines.extend(sections(exports, nodes, source_lines))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed reference differs from the generated output",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual == expected:
            return 0
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(OUTPUT),
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff))
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
